[package]
name = "didc"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
candid = "0.10.0"
candid_parser = "0.1.0"

[profile.release]
lto = true
opt-level = 'z'
